ci:
- changed-files:
  - any-glob-to-any-file: ".github/**"

data:
- changed-files:
  - any-glob-to-any-file: "hypertorch/data/**"

docs:
- changed-files:
  - any-glob-to-any-file:
    - "docs/**"
    - "examples/**"
    - "*.md"
- head-branch: ["^docs"]

models:
- changed-files:
  - any-glob-to-any-file:
    - "hypertorch/hlp/**"
    - "hypertorch/models/**"
    - "hypertorch/nn/**"

tests:
- changed-files:
  - any-glob-to-any-file: "hypertorch/tests/**"

training:
- changed-files:
  - any-glob-to-any-file: "hypertorch/train/**"

types:
- changed-files:
  - any-glob-to-any-file: "hypertorch/types/**"

utils:
- changed-files:
  - any-glob-to-any-file: "hypertorch/utils/**"

feature:
- head-branch: ["^feat"]

fix:
- head-branch: ["^fix"]

chore:
- head-branch: ["^chore"]

refactoring:
- head-branch: ["^refactor"]
