from torch import Tensor, nn
from torch.utils.data import DataLoader
from typing import TypedDict
from typing_extensions import NotRequired
from torch_geometric.nn import Node2Vec as PyGNode2Vec

from hyperbench.models.gcn import GCN, GCNConfig


class Node2Vec(nn.Module):
    """
    Node2Vec implementation based on ``torch_geometric.nn.Node2Vec``.

    Attributes:
        model: ``torch_geometric.nn.Node2Vec`` model.
    """

    def __init__(
        self,
        edge_index: Tensor,
        embedding_dim: int,
        walk_length: int = 20,
        context_size: int = 10,
        num_walks_per_node: int = 10,
        p: float = 1.0,
        q: float = 1.0,
        num_negative_samples: int = 1,
        num_nodes: int | None = None,
        sparse: bool = True,
    ):
        """
        Initialize the Node2Vec model.

        Args:
            edge_index: Edge index representing the graph structure. Size ``(2, num_edges)``.
            embedding_dim: Dimension of the node embeddings to learn.
            walk_length: Length of each random walk.
            context_size: Window size for the skip-gram model (number of neighbors in the walk
                considered as context).
                For example, if ``context_size=2`` and ``walk_length=5``, then for
                a random walk ``[v0, v1, v2, v3, v4]``,
                the context for ``v2`` would be ``[v0, v1, v3, v4]`` as we take neighbors within
                distance 2 in the walk.
                The pairs generated by skip-gram would be
                ``[(v2, v0), (v2, v1), (v2, v3), (v2, v4)]``.
                Rule of thumb: Graphs with strong local structure (5-10), Graphs with
                communities/long-range patterns (10-20).
                Defaults to ``10``.
            num_walks_per_node: Number of random walks to start at each node.
            p: Return hyperparameter for Node2Vec. Default is ``1.0`` (unbiased).
                This controls the probability of stepping back to the node visited in the previous
                step. Lower values of ``p`` make immediate backtracking more likely, which keeps
                walks closer to the local neighborhood. Higher values of ``p`` discourage returning
                to the previous node, so walks are less likely to bounce back and forth across
                the same edge.
            q: In-out hyperparameter for Node2Vec. Default is ``1.0`` (unbiased).
                This controls whether walks stay near the source node or explore further outward.
                Lower values of ``q`` bias the walk toward outward exploration, behaving more like
                DFS and emphasizing structural roles. Higher values of ``q`` bias the walk toward
                nearby nodes, behaving more like BFS and emphasizing community
                structure and homophily.
            num_negative_samples: Number of negative samples to use for training the
                skip-gram model. If set to ``X``, then for each positive pair ``(u, v)`` generated
                from the random walks, ``X`` negative pairs ``(u, v_neg)`` will be generated,
                where ``v_neg`` is a node sampled uniformly at random from all nodes in the graph.
                Defaults to ``1``, meaning one negative sample per positive pair.
            num_nodes: Total number of nodes in the graph. If not provided, it will be inferred from
                ``hyperedge_index``. This is only needed if ``hyperedge_index`` does not include all
                nodes (e.g., some isolated nodes are missing).
            sparse: Whether Node2Vec embeddings should use sparse gradients.

        Raises:
            ValueError: If ``walk_length`` is smaller than ``context_size``.
        """
        super().__init__()
        if walk_length < context_size:
            raise ValueError(
                "Expected walk_length >= context_size, got "
                f"walk_length={walk_length}, context_size={context_size}."
            )

        self.model = PyGNode2Vec(
            edge_index=edge_index,
            embedding_dim=embedding_dim,
            walk_length=walk_length,
            context_size=context_size,
            walks_per_node=num_walks_per_node,
            p=p,
            q=q,
            num_negative_samples=num_negative_samples,
            num_nodes=num_nodes,
            sparse=sparse,
        )

    def forward(self, batch: Tensor | None = None) -> Tensor:
        """
        Return Node2Vec embeddings for optional node batches.

        Args:
            batch: Optional node IDs to embed. Defaults to ``None``.

        Returns:
            embeddings: Node embeddings.
        """
        return self.model(batch)

    @property
    def num_embeddings(self) -> int:
        """
        Return the number of embedding rows.

        Returns:
            num_embeddings: Number of node embeddings.
        """
        return int(self.model.embedding.num_embeddings)

    def loss(self, pos_rw: Tensor, neg_rw: Tensor) -> Tensor:
        """
        Compute the Node2Vec random-walk loss.

        Args:
            pos_rw: Positive random walks.
            neg_rw: Negative random walks.

        Returns:
            loss: Scalar Node2Vec loss.
        """
        return self.model.loss(pos_rw, neg_rw)

    def loader(self, batch_size: int = 128, shuffle: bool = True) -> DataLoader:
        """
        Create the Node2Vec random-walk loader.

        Args:
            batch_size: Number of walk starts per batch.
            shuffle: Whether to shuffle walk starts. Defaults to ``True``.

        Returns:
            loader: Random-walk data loader.
        """
        return self.model.loader(batch_size=batch_size, shuffle=shuffle)


class Node2VecConfig(TypedDict):
    """
    Configuration for the Node2Vec model.

    Attributes:
        edge_index: Edge index representing the graph structure. Size ``(2, num_edges)``.
        embedding_dim: Dimension of the node embeddings to learn.
        walk_length: Length of each random walk.
        context_size: Window size for the skip-gram model (number of neighbors in the walk
            considered as context).
            For example, if ``context_size=2`` and ``walk_length=5``, then for a
            random walk ``[v0, v1, v2, v3, v4]``,
            the context for ``v2`` would be ``[v0, v1, v3, v4]`` as we take neighbors within
            distance 2 in the walk.
            The pairs generated by skip-gram would be ``[(v2, v0), (v2, v1), (v2, v3), (v2, v4)]``.
            Rule of thumb: Graphs with strong local structure (5-10), Graphs with
            communities/long-range patterns (10-20).
            Defaults to ``10``.
        num_walks_per_node: Number of random walks to start at each node.
        p: Return hyperparameter for Node2Vec. Default is ``1.0`` (unbiased).
            This controls the probability of stepping back to the node visited in the previous step.
            Lower values of ``p`` make immediate backtracking more likely, which keeps walks
            closer to the local neighborhood. Higher values of ``p`` discourage returning to the
            previous node, so walks are less likely to bounce back and forth across the same edge.
        q: In-out hyperparameter for Node2Vec. Default is ``1.0`` (unbiased).
            This controls whether walks stay near the source node or explore further outward.
            Lower values of ``q`` bias the walk toward outward exploration, behaving more like
            DFS and emphasizing structural roles. Higher values of ``q`` bias the walk toward
            nearby nodes, behaving more like BFS and emphasizing community structure and homophily.
        num_negative_samples: Number of negative samples to use for training the skip-gram model.
            If set to ``X``, then for each positive pair ``(u, v)`` generated from the random walks,
            ``X`` negative pairs ``(u, v_neg)`` will be generated, where ``v_neg`` is a node sampled
             uniformly at random from all nodes in the graph.
            Defaults to ``1``, meaning one negative sample per positive pair.
        num_nodes: Total number of nodes in the graph. If not provided, it will be inferred from
            the hyperedge_index.
            This is only needed if the hyperedge_index does not include all nodes
            (e.g., some isolated nodes are missing).
        sparse: Whether Node2Vec embeddings should use sparse gradients.
    """

    edge_index: Tensor
    embedding_dim: int
    context_size: NotRequired[int]
    walk_length: NotRequired[int]
    num_walks_per_node: NotRequired[int]
    p: NotRequired[float]
    q: NotRequired[float]
    num_negative_samples: NotRequired[int]
    num_nodes: NotRequired[int]
    sparse: NotRequired[bool]


class Node2VecGCN(nn.Module):
    """
    A joint encoder that first learns Node2Vec embeddings and then refines them with GCN layers.

    Attributes:
        node2vec: Internal Node2Vec encoder.
        gcn: GCN stack applied to Node2Vec embeddings.
    """

    def __init__(
        self,
        node2vec_config: Node2VecConfig,
        gcn_config: GCNConfig,
    ):
        """
        Initialize the joint Node2Vec-GCN encoder.

        Args:
            node2vec_config: Configuration for the internal ``Node2Vec`` encoder.
            gcn_config: Configuration for the GCN stack.
        """
        super().__init__()
        self.node2vec = Node2Vec(**node2vec_config)
        self.gcn = GCN(**gcn_config)

    def forward(
        self,
        batch: Tensor | None = None,
        edge_index: Tensor | None = None,
    ) -> Tensor:
        """
        Compute Node2Vec embeddings and refine them with GCN layers.

        Args:
            batch: Optional node IDs passed to the Node2Vec encoder.
            edge_index: Edge index used by the GCN stack. Defaults to ``None``.

        Returns:
            embeddings: GCN-refined node embeddings.

        Raises:
            ValueError: If ``edge_index`` is not provided.
        """
        if edge_index is None:
            raise ValueError("Node2VecGCN requires edge_index in forward().")

        node_embeddings = self.node2vec(batch)
        return self.gcn(node_embeddings, edge_index)

    @property
    def num_embeddings(self) -> int:
        """
        Return the number of Node2Vec embedding rows.

        Returns:
            num_embeddings: Number of node embeddings.
        """
        return self.node2vec.num_embeddings

    def loss(self, pos_rw: Tensor, neg_rw: Tensor) -> Tensor:
        """
        Compute the Node2Vec random-walk loss.

        Args:
            pos_rw: Positive random walks.
            neg_rw: Negative random walks.

        Returns:
            loss: Scalar Node2Vec loss.
        """
        return self.node2vec.loss(pos_rw, neg_rw)

    def loader(self, batch_size: int = 128, shuffle: bool = True) -> DataLoader:
        """
        Create the Node2Vec random-walk loader.

        Args:
            batch_size: Number of walk starts per batch.
            shuffle: Whether to shuffle walk starts. Defaults to ``True``.

        Returns:
            loader: Random-walk data loader.
        """
        return self.node2vec.loader(batch_size=batch_size, shuffle=shuffle)
