from torch import Tensor, nn
from torch.utils.data import DataLoader
from typing import Literal, TypeAlias, TypedDict
from collections.abc import Iterator
from typing_extensions import NotRequired
from hypertorch.models.gcn import GCN, GCNConfig
from hypertorch.models.node2vec import Node2Vec, Node2VecConfig, Node2VecGCN
from hypertorch.types import (
    EdgeIndex,
    HyperedgeIndex,
    GraphReductionStrategy,
    GraphReductionStrategyEnum,
)
from hypertorch.utils import ActivationFn


NODE2VEC_JOINT_MODE = "joint"
NODE2VEC_PRECOMPUTED_MODE = "precomputed"

Node2VecMode: TypeAlias = Literal["precomputed", "joint"]
"""Training mode for Node2Vec-based encoders."""


class Node2VecGCNEncoderConfig(TypedDict):
    """
    Configuration for the GCN model.

    Attributes:
        out_channels: Dimension of the output node embeddings from the GCN layers.
        hidden_channels: Dimension of the hidden node embeddings in the GCN layers.
        num_layers: Number of GCN layers. Must be at least 1. Defaults to ``2``.
        drop_rate: Dropout rate applied after each GCN layer (except the last one).
            Defaults to ``0.0`` (no dropout).
        bias: Whether to include a bias term in the GCN layers. Defaults to ``True``.
        improved: Whether to use the improved version of GCNConv. Defaults to ``False``.
        add_self_loops: Whether to add self-loops to the input graph. Defaults to ``True``.
        normalize: Whether to symmetrically normalize the adjacency matrix in GCNConv.
            Defaults to ``True``.
        cached: Whether to cache the normalized adjacency matrix in GCNConv.
            Only applicable if the graph structure does not change between epochs.
            Defaults to ``False``.
        graph_reduction_strategy: Strategy for reducing the hyperedge graph.
            Defaults to ``clique_expansion``.
        num_nodes: Total number of nodes in the hypergraph. This is useful when setting is
            transductive but train dataset may not contain all hyperedges where some nodes appear,
            to ensure consistent encoding across splits.
        activation_fn: Activation function to use after each hidden layer.
            Defaults to ``nn.ReLU``.
        activation_fn_kwargs: Keyword arguments for the activation function.
            Defaults to empty dict.
    """

    out_channels: int
    hidden_channels: NotRequired[int]
    num_layers: NotRequired[int]
    drop_rate: NotRequired[float]
    bias: NotRequired[bool]
    improved: NotRequired[bool]
    add_self_loops: NotRequired[bool]
    normalize: NotRequired[bool]
    cached: NotRequired[bool]
    graph_reduction_strategy: NotRequired[GraphReductionStrategy]
    num_nodes: NotRequired[int]
    activation_fn: NotRequired[ActivationFn]
    activation_fn_kwargs: NotRequired[dict]


class Node2VecEncoderConfig(TypedDict):
    """
    Configuration for the Node2Vec encoder.

    Attributes:
        context_size: Skip-gram context size for Node2Vec.
            For example, if ``context_size=2`` and ``walk_length=5``, then for a
            random walk ``[v0, v1, v2, v3, v4]``,
            the context for ``v2`` would be ``[v0, v1, v3, v4]`` as we take neighbors within
            distance 2 in the walk.
            The pairs generated by skip-gram would be ``[(v2, v0), (v2, v1), (v2, v3), (v2, v4)]``.
            Rule of thumb: Graphs with strong local structure (5-10), Graphs with
            communities/long-range patterns (10-20).
            Defaults to ``10``.
        walk_length: Length of each random walk.
        num_walks_per_node: Number of walks sampled per node.
        p: Node2Vec return parameter. Controls the probability of stepping back to the node visited
            in the previous step. Lower values of ``p`` make immediate backtracking more likely,
            while higher values discourage returning to the previous node.
        q: Node2Vec in-out parameter. Controls whether walks stay near the source node or explore
            further outward. Lower values of ``q`` bias the walk toward DFS-like exploration and
            structural similarity, while higher values bias it toward BFS-like exploration and
            local community structure and homophily.
        num_negative_samples: Number of negative samples per positive walk context.
            If set to ``X``, then for each positive pair ``(u, v)`` generated from the random walks,
            ``X`` negative pairs ``(u, v_neg)`` will be generated,
            where ``v_neg`` is a node sampled uniformly at random from all nodes in the graph.
            Defaults to ``1``, meaning one negative sample per positive pair.
        num_nodes: Number of nodes in the stable node space. Defaults to the number of nodes
            in the ``hyperedge_index`` if not provided.
        train_hyperedge_index: Training hypereddge index used to build the Node2Vec walk graph.
            Required in ``joint`` mode.
        graph_reduction_strategy: Strategy for reducing the hyperedge graph.
            Defaults to ``clique_expansion``.
        random_walk_batch_size: Batch size used by the walk sampler in joint mode.
        node2vec_loss_weight: Weight applied to the Node2Vec walk loss in joint mode.
            This is to decide how much the loss of Node2Vec contributes to the overall loss in
            joint training, relative to the task loss.
            Defaults to ``1.0`` (equal weighting). Set to a higher value to prioritize learning
            good node embeddings, or a lower value to prioritize the task loss.
            Ignored in precomputed mode.
        sparse: Whether to use sparse gradients in the Node2Vec encoder. Defaults to ``False``.
    """

    context_size: NotRequired[int]
    walk_length: NotRequired[int]
    num_walks_per_node: NotRequired[int]
    p: NotRequired[float]
    q: NotRequired[float]
    num_negative_samples: NotRequired[int]
    num_nodes: NotRequired[int]
    train_hyperedge_index: NotRequired[Tensor]
    graph_reduction_strategy: NotRequired[GraphReductionStrategy]
    random_walk_batch_size: NotRequired[int]
    node2vec_loss_weight: NotRequired[float]
    sparse: NotRequired[bool]


class Node2VecWalkLoaderState:
    """
    State object to hold the walk loader and its iterator for joint Node2Vec training.

    Attributes:
        walk_loader: The DataLoader that provides batches of random walks from the Node2Vec encoder
            during joint training. Initialized lazily when first needed.
        cached_walk_loader_iterator: An iterator over the walk_loader, cached to allow
            fetching the next batch of walks at each training step without reinitializing.
    """

    walk_loader: DataLoader | None = None
    cached_walk_loader_iterator: Iterator | None = None


Node2VecEncoder: TypeAlias = Node2Vec | Node2VecGCN
"""Supported Node2Vec encoder implementations."""


def build_gcn_encoder(embedding_dim: int, gcn_config: Node2VecGCNEncoderConfig) -> GCN:
    """
    Build a GCN encoder for precomputed mode.

    Args:
        embedding_dim: Input embedding dimension.
        gcn_config: GCN configuration.

    Returns:
        encoder: GCN encoder.
    """
    return GCN(**to_gcn_config(embedding_dim, gcn_config))


def build_node2vec_encoder(
    embedding_dim: int,
    node2vec_config: Node2VecEncoderConfig,
    mode: Node2VecMode,
) -> Node2Vec:
    """
    Build a joint-mode Node2Vec encoder.

    Args:
        embedding_dim: Node2Vec embedding dimension.
        node2vec_config: Node2Vec configuration.
        mode: Node2Vec training mode used in validation errors.

    Returns:
        encoder: Node2Vec encoder.
    """
    return Node2Vec(**to_model_node2vec_config(embedding_dim, node2vec_config, mode))


def build_node2vecgcn_encoder(
    embedding_dim: int,
    node2vec_config: Node2VecEncoderConfig,
    gcn_config: Node2VecGCNEncoderConfig,
    mode: Node2VecMode,
) -> Node2VecGCN:
    """
    Build a joint-mode Node2Vec-GCN encoder.

    Args:
        embedding_dim: Node2Vec embedding dimension.
        node2vec_config: Node2Vec configuration.
        gcn_config: GCN configuration.
        mode: Node2Vec training mode used in validation errors.

    Returns:
        encoder: Joint Node2Vec-GCN encoder.
    """
    return Node2VecGCN(
        node2vec_config=to_model_node2vec_config(embedding_dim, node2vec_config, mode),
        gcn_config=to_gcn_config(embedding_dim, gcn_config),
    )


def get_walk_loader(
    mode: Node2VecMode,
    encoder: nn.Module | None,
    batch_size: int,
    state: Node2VecWalkLoaderState,
) -> DataLoader | None:
    """
    Return or initialize the Node2Vec walk loader for joint mode.

    Args:
        mode: Node2Vec training mode.
        encoder: Optional encoder module.
        batch_size: Random-walk loader batch size.
        state: Mutable walk-loader state.

    Returns:
        loader: Walk loader in joint mode, otherwise ``None``.
    """
    if mode != NODE2VEC_JOINT_MODE:
        return None

    if state.walk_loader is None:
        state.walk_loader = to_node2vec_encoder(encoder, mode).loader(
            batch_size=batch_size,
            shuffle=True,
        )
        state.cached_walk_loader_iterator = iter(state.walk_loader)

    return state.walk_loader


def next_walk_batch(
    mode: Node2VecMode,
    encoder: nn.Module | None,
    batch_size: int,
    state: Node2VecWalkLoaderState,
) -> tuple[Tensor, Tensor]:
    """
    Return the next Node2Vec random-walk batch.

    Args:
        mode: Node2Vec training mode.
        encoder: Optional encoder module.
        batch_size: Random-walk loader batch size.
        state: Mutable walk-loader state.

    Returns:
        batch: Positive and negative random-walk tensors.

    Raises:
        ValueError: If the joint-mode walk loader cannot be initialized.
    """
    get_walk_loader(mode, encoder, batch_size, state)
    if state.walk_loader is None or state.cached_walk_loader_iterator is None:
        raise ValueError("Joint Node2Vec mode could not initialize the walk loader.")

    try:
        return next(state.cached_walk_loader_iterator)
    except StopIteration:
        state.cached_walk_loader_iterator = iter(state.walk_loader)
        return next(state.cached_walk_loader_iterator)


def to_node2vec_edge_index(
    node2vec_config: Node2VecEncoderConfig,
    mode: Node2VecMode,
) -> tuple[Tensor, int]:
    """
    Build the Node2Vec graph edge index from a training hypergraph.

    Args:
        node2vec_config: Shared Node2Vec configuration.
        mode: Node2Vec training mode.

    Returns:
        edge_index: Reduced graph edge index without self-loops.
        num_nodes: Number of nodes in the stable node space.

    Raises:
        ValueError: If ``train_hyperedge_index`` is missing.
    """
    if "train_hyperedge_index" not in node2vec_config:
        raise ValueError(f"Node2Vec in mode {mode} requires train_hyperedge_index.")

    reduced_edge_index = HyperedgeIndex(node2vec_config["train_hyperedge_index"]).reduce(
        strategy=node2vec_config.get(
            "graph_reduction_strategy", GraphReductionStrategyEnum.CLIQUE_EXPANSION
        ),
        num_nodes=node2vec_config.get("num_nodes"),
    )
    edge_index_wrapper = EdgeIndex(reduced_edge_index).remove_selfloops()
    num_nodes = node2vec_config.get("num_nodes", edge_index_wrapper.num_nodes)
    return edge_index_wrapper.item, num_nodes


def to_gcn_edge_index(
    hyperedge_index: Tensor,
    gcn_config: Node2VecGCNEncoderConfig,
) -> Tensor:
    """
    Reduce a hyperedge index to the graph edge index used by GCN.

    Args:
        hyperedge_index: Hyperedge incidence tensor.
        gcn_config: GCN configuration.

    Returns:
        edge_index: Reduced graph edge index without self-loops.
    """
    graph_reduction_strategy = gcn_config.get(
        "graph_reduction_strategy", GraphReductionStrategyEnum.CLIQUE_EXPANSION
    )
    reduced_gcn_edge_index = HyperedgeIndex(hyperedge_index).reduce(
        strategy=graph_reduction_strategy,
        num_nodes=gcn_config.get("num_nodes"),
    )
    return EdgeIndex(reduced_gcn_edge_index).remove_selfloops().item


def to_gcn_config(embedding_dim: int, gcn_config: Node2VecGCNEncoderConfig) -> GCNConfig:
    """
    Convert a shared GCN config into a model GCN config.

    Args:
        embedding_dim: Node2Vec embedding dimension used as GCN input size.
        gcn_config: Shared GCN configuration.

    Returns:
        gcn_config: Model-side GCN configuration.
    """
    model_gcn_config: GCNConfig = {
        "in_channels": embedding_dim,
        "out_channels": gcn_config["out_channels"],
        "hidden_channels": gcn_config.get("hidden_channels", embedding_dim),
        "num_layers": gcn_config.get("num_layers", 2),
        "drop_rate": gcn_config.get("drop_rate", 0.0),
        "bias": gcn_config.get("bias", True),
        "improved": gcn_config.get("improved", False),
        "add_self_loops": gcn_config.get("add_self_loops", True),
        "normalize": gcn_config.get("normalize", True),
        "cached": gcn_config.get("cached", False),
    }
    if "activation_fn" in gcn_config:
        model_gcn_config["activation_fn"] = gcn_config["activation_fn"]
    if "activation_fn_kwargs" in gcn_config:
        model_gcn_config["activation_fn_kwargs"] = gcn_config["activation_fn_kwargs"]
    return model_gcn_config


def to_model_node2vec_config(
    embedding_dim: int,
    node2vec_config: Node2VecEncoderConfig,
    mode: Node2VecMode,
) -> Node2VecConfig:
    """
    Convert a shared Node2Vec config into a model Node2Vec config.

    Args:
        embedding_dim: Node2Vec embedding dimension.
        node2vec_config: Shared Node2Vec configuration.
        mode: Node2Vec training mode used in validation errors.

    Returns:
        node2vec_config: Model-side Node2Vec configuration.
    """
    validate_walk_length_and_context_size(
        walk_length=node2vec_config.get("walk_length", 20),
        context_size=node2vec_config.get("context_size", 10),
    )
    edge_index, num_nodes = to_node2vec_edge_index(node2vec_config, mode)

    return {
        "edge_index": edge_index,
        "embedding_dim": embedding_dim,
        "walk_length": node2vec_config.get("walk_length", 20),
        "context_size": node2vec_config.get("context_size", 10),
        "num_walks_per_node": node2vec_config.get("num_walks_per_node", 10),
        "p": node2vec_config.get("p", 1.0),
        "q": node2vec_config.get("q", 1.0),
        "num_negative_samples": node2vec_config.get("num_negative_samples", 1),
        "num_nodes": num_nodes,
        "sparse": node2vec_config.get("sparse", False),
    }


def to_node2vec_encoder(encoder: nn.Module | None, mode: Node2VecMode) -> Node2VecEncoder:
    """
    Validate and return a Node2Vec-compatible encoder.

    Args:
        encoder: Optional encoder module.
        mode: Node2Vec training mode used in error messages.

    Returns:
        encoder: Node2Vec or Node2VecGCN encoder.

    Raises:
        ValueError: If the encoder is missing or incompatible.
    """
    if encoder is None or not isinstance(encoder, (Node2Vec, Node2VecGCN)):
        raise ValueError(
            f"Node2Vec in mode {mode} requires a Node2Vec encoder, but none was provided."
        )
    return encoder


def to_node2vecgcn_encoder(encoder: nn.Module | None, mode: Node2VecMode) -> Node2VecGCN:
    """
    Validate and return a Node2Vec-GCN encoder.

    Args:
        encoder: Optional encoder module.
        mode: Node2Vec training mode used in error messages.

    Returns:
        encoder: Node2Vec-GCN encoder.

    Raises:
        ValueError: If the encoder is missing or incompatible.
    """
    if encoder is None or not isinstance(encoder, Node2VecGCN):
        raise ValueError(
            f"Node2Vec-GCN in mode {mode} requires a Node2VecGCN encoder, but none was provided."
        )
    return encoder


def validate_global_node_ids(
    num_embeddings: int,
    global_node_ids: Tensor | None,
    mode: Node2VecMode,
) -> None:
    """
    Validate global node IDs used to index a Node2Vec embedding table.

    Args:
        num_embeddings: Number of rows in the Node2Vec embedding table.
        global_node_ids: Optional global node IDs from a batch.
        mode: Node2Vec training mode used in error messages.

    Raises:
        ValueError: If IDs are missing or outside the embedding table range.
    """
    if global_node_ids is None or len(global_node_ids) < 1:
        raise ValueError(f"Node2Vec in mode {mode} requires batch.global_node_ids.")

    min_global_node_id = int(global_node_ids.min().item())
    max_global_node_id = int(global_node_ids.max().item())

    max_acceptable_node_id = num_embeddings - 1
    if min_global_node_id < 0 or max_global_node_id > max_acceptable_node_id:
        raise ValueError(
            f"Node2Vec in mode {mode} cannot index the provided batch.global_node_ids. "
            f"Expected IDs in [0, {max_acceptable_node_id}], got "
            f"[{min_global_node_id}, {max_global_node_id}]. "
            "Set encoder_config['node2vec_config']['num_nodes'] for the full stable node space."
        )


def validate_walk_length_and_context_size(walk_length: int, context_size: int) -> None:
    """
    Validate Node2Vec walk and context lengths.

    Args:
        walk_length: Random walk length.
        context_size: Skip-gram context size.

    Raises:
        ValueError: If ``walk_length`` is smaller than ``context_size``.
    """
    if walk_length < context_size:
        raise ValueError(
            f"Expected walk_length >= context_size, got "
            f"walk_length={walk_length}, context_size={context_size}."
        )
