default_install_hook_types:
  - pre-commit
  - commit-msg

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: name-tests-test
        exclude: "hyperbench/tests/mock/"
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
      - id: trailing-whitespace

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, chore, refactor]

  - repo: local
    hooks:
      - id: uvx-ruff-format
        name: uvx ruff format
        entry: bash -c 'uvx ruff format'
        language: system
        types_or: [python, pyi]
        require_serial: true

  - repo: local
    hooks:
      - id: uvx-ty-check
        name: uvx ty check
        entry: bash -c 'uvx ty check'
        language: system
        types_or: [python, pyi]
        require_serial: true
