from torch import Tensor, nn
from torch.utils.data import DataLoader
from typing import Dict, Iterator, Literal, Optional, Tuple, TypeAlias, TypedDict
from typing_extensions import NotRequired
from hyperbench.models import GCNConfig, Node2Vec, Node2VecGCN
from hyperbench.types import EdgeIndex, HyperedgeIndex
from hyperbench.utils import ActivationFn


NODE2VEC_JOINT_MODE = "joint"
NODE2VEC_PRECOMPUTED_MODE = "precomputed"

Node2VecMode: TypeAlias = Literal["precomputed", "joint"]


class Node2VecGCNHlpConfig(TypedDict):
    """
    Configuration for the GCN model.

    Args:
        out_channels: Dimension of the output node embeddings from the GCN layers.
        hidden_channels: Dimension of the hidden node embeddings in the GCN layers.
        num_layers: Number of GCN layers. Must be at least 1. Defaults to ``2``.
        drop_rate: Dropout rate applied after each GCN layer (except the last one). Defaults to ``0.0`` (no dropout).
        bias: Whether to include a bias term in the GCN layers. Defaults to ``True``.
        improved: Whether to use the improved version of GCNConv. Defaults to ``False``.
        add_self_loops: Whether to add self-loops to the input graph. Defaults to ``True``.
        normalize: Whether to symmetrically normalize the adjacency matrix in GCNConv. Defaults to ``True``.
        cached: Whether to cache the normalized adjacency matrix in GCNConv.
            Only applicable if the graph structure does not change between epochs. Defaults to ``False``.
        graph_reduction_strategy: Strategy for reducing the hyperedge graph. Defaults to ``clique_expansion``.
        activation_fn: Activation function to use after each hidden layer. Defaults to ``nn.ReLU``.
        activation_fn_kwargs: Keyword arguments for the activation function. Defaults to empty dict.
    """

    out_channels: int
    hidden_channels: NotRequired[int]
    num_layers: NotRequired[int]
    drop_rate: NotRequired[float]
    bias: NotRequired[bool]
    improved: NotRequired[bool]
    add_self_loops: NotRequired[bool]
    normalize: NotRequired[bool]
    cached: NotRequired[bool]
    graph_reduction_strategy: NotRequired[Literal["clique_expansion"]]
    activation_fn: NotRequired[ActivationFn]
    activation_fn_kwargs: NotRequired[Dict]


class Node2VecHlpConfig(TypedDict):
    """
    Configuration for the Node2Vec encoder.

    Args:
        context_size: Skip-gram context size for Node2Vec.
            For example, if ``context_size=2`` and ``walk_length=5``, then for a random walk ``[v0, v1, v2, v3, v4]``,
            the context for ``v2`` would be ``[v0, v1, v3, v4]`` as we take neighbors within distance 2 in the walk.
            The pairs generated by skip-gram would be ``[(v2, v0), (v2, v1), (v2, v3), (v2, v4)]``.
            Rule of thumb: Graphs with strong local structure (5-10), Graphs with communities/long-range patterns (10-20).
            Defaults to ``10``.
        walk_length: Length of each random walk.
        num_walks_per_node: Number of walks sampled per node.
        p: Node2Vec return parameter. Controls the probability of stepping back to the node visited
            in the previous step. Lower values of ``p`` make immediate backtracking more likely,
            while higher values discourage returning to the previous node.
        q: Node2Vec in-out parameter. Controls whether walks stay near the source node or explore
            further outward. Lower values of ``q`` bias the walk toward DFS-like exploration and
            structural similarity, while higher values bias it toward BFS-like exploration and
            local community structure and homophily.
        num_negative_samples: Number of negative samples per positive walk context.
            If set to ``X``, then for each positive pair ``(u, v)`` generated from the random walks,
            ``X`` negative pairs ``(u, v_neg)`` will be generated,
            where ``v_neg`` is a node sampled uniformly at random from all nodes in the graph.
            Defaults to ``1``, meaning one negative sample per positive pair.
        num_nodes: Number of nodes in the stable node space. Defaults to the number of nodes in the ``hyperedge_index`` if not provided.
        train_hyperedge_index: Training hypereddge index used to build the Node2Vec walk graph. Required in ``joint`` mode.
        graph_reduction_strategy: Strategy for reducing the hyperedge graph. Defaults to ``clique_expansion``.
        random_walk_batch_size: Batch size used by the walk sampler in joint mode.
        node2vec_loss_weight: Weight applied to the Node2Vec walk loss in joint mode.
            This is to decide how much the loss of Node2Vec contributes to the overall loss in joint training, relative to the HLP loss.
             Defaults to ``1.0`` (equal weighting). Set to a higher value to prioritize learning good node embeddings,
             or a lower value to prioritize the HLP loss. Ignored in precomputed mode.
        sparse: Whether to use sparse gradients in the Node2Vec encoder. Defaults to ``False``.
    """

    context_size: NotRequired[int]
    walk_length: NotRequired[int]
    num_walks_per_node: NotRequired[int]
    p: NotRequired[float]
    q: NotRequired[float]
    num_negative_samples: NotRequired[int]
    num_nodes: NotRequired[int]
    train_hyperedge_index: NotRequired[Tensor]
    graph_reduction_strategy: NotRequired[Literal["clique_expansion"]]
    random_walk_batch_size: NotRequired[int]
    node2vec_loss_weight: NotRequired[float]
    sparse: NotRequired[bool]


class Node2VecWalkLoaderState:
    """
    State object to hold the walk loader and its iterator for joint Node2Vec training.

    Args:
        walk_loader: The DataLoader that provides batches of random walks from the Node2Vec encoder during joint training.
            Initialized lazily when first needed.
        cached_walk_loader_iterator: An iterator over the walk_loader, cached to allow
            fetching the next batch of walks at each training step without reinitializing.
    """

    walk_loader: Optional[DataLoader] = None
    cached_walk_loader_iterator: Optional[Iterator] = None


Node2VecEncoder: TypeAlias = Node2Vec | Node2VecGCN


def _get_walk_loader(
    mode: Node2VecMode,
    encoder: Optional[nn.Module],
    batch_size: int,
    state: Node2VecWalkLoaderState,
) -> Optional[DataLoader]:
    if mode != NODE2VEC_JOINT_MODE:
        return None

    if state.walk_loader is None:
        state.walk_loader = _to_node2vec_encoder(encoder, mode).loader(
            batch_size=batch_size,
            shuffle=True,
        )
        state.cached_walk_loader_iterator = iter(state.walk_loader)

    return state.walk_loader


def _next_walk_batch(
    mode: Node2VecMode,
    encoder: Optional[nn.Module],
    batch_size: int,
    state: Node2VecWalkLoaderState,
):
    _get_walk_loader(mode, encoder, batch_size, state)
    if state.walk_loader is None or state.cached_walk_loader_iterator is None:
        raise ValueError("Joint Node2Vec mode could not initialize the walk loader.")

    try:
        return next(state.cached_walk_loader_iterator)
    except StopIteration:
        state.cached_walk_loader_iterator = iter(state.walk_loader)
        return next(state.cached_walk_loader_iterator)


def _to_node2vec_edge_index(
    node2vec_config: Node2VecHlpConfig,
    mode: Node2VecMode,
) -> Tuple[Tensor, int]:
    if "train_hyperedge_index" not in node2vec_config:
        raise ValueError(f"Node2Vec in mode {mode} requires train_hyperedge_index.")

    reduced_edge_index = HyperedgeIndex(node2vec_config["train_hyperedge_index"]).reduce(
        strategy=node2vec_config.get("graph_reduction_strategy", "clique_expansion")
    )
    edge_index_wrapper = EdgeIndex(reduced_edge_index).remove_selfloops()
    num_nodes = node2vec_config.get("num_nodes", edge_index_wrapper.num_nodes)
    return edge_index_wrapper.item, num_nodes


def _to_gcn_config(embedding_dim: int, gcn_hlp_config: Node2VecGCNHlpConfig) -> GCNConfig:
    gcn_config: GCNConfig = {
        "in_channels": embedding_dim,
        "out_channels": gcn_hlp_config["out_channels"],
        "hidden_channels": gcn_hlp_config.get("hidden_channels", embedding_dim),
        "num_layers": gcn_hlp_config.get("num_layers", 2),
        "drop_rate": gcn_hlp_config.get("drop_rate", 0.0),
        "bias": gcn_hlp_config.get("bias", True),
        "improved": gcn_hlp_config.get("improved", False),
        "add_self_loops": gcn_hlp_config.get("add_self_loops", True),
        "normalize": gcn_hlp_config.get("normalize", True),
        "cached": gcn_hlp_config.get("cached", False),
    }
    if "activation_fn" in gcn_hlp_config:
        gcn_config["activation_fn"] = gcn_hlp_config["activation_fn"]
    if "activation_fn_kwargs" in gcn_hlp_config:
        gcn_config["activation_fn_kwargs"] = gcn_hlp_config["activation_fn_kwargs"]
    return gcn_config


def _to_node2vec_encoder(encoder: Optional[nn.Module], mode: Node2VecMode) -> Node2VecEncoder:
    if encoder is None or not isinstance(encoder, (Node2Vec, Node2VecGCN)):
        raise ValueError(f"Node2Vec in mode {mode} requires an encoder, but none was provided.")
    return encoder


def _validate_global_node_ids(
    num_embeddings: int,
    global_node_ids: Optional[Tensor],
    mode: Node2VecMode,
) -> None:
    if global_node_ids is None or len(global_node_ids) < 1:
        raise ValueError(f"Node2Vec in mode {mode} requires batch.global_node_ids.")

    min_global_node_id = int(global_node_ids.min().item())
    max_global_node_id = int(global_node_ids.max().item())

    max_acceptable_node_id = num_embeddings - 1
    if min_global_node_id < 0 or max_global_node_id > max_acceptable_node_id:
        raise ValueError(
            f"Node2Vec in mode {mode} cannot index the provided batch.global_node_ids. "
            f"Expected IDs in [0, {max_acceptable_node_id}], got "
            f"[{min_global_node_id}, {max_global_node_id}]. "
            "Set encoder_config['node2vec_config']['num_nodes'] for the full stable node space."
        )


def _validate_walk_length_and_context_size(walk_length: int, context_size: int) -> None:
    if walk_length < context_size:
        raise ValueError(
            f"Expected walk_length >= context_size, got "
            f"walk_length={walk_length}, context_size={context_size}."
        )
