from torch import Tensor, nn, optim
from torch.utils.data import DataLoader
from typing import Iterator, Literal, Optional, TypedDict
from typing_extensions import NotRequired
from torchmetrics import MetricCollection
from hyperbench.models import Node2Vec, SLP
from hyperbench.types import EdgeIndex, HData, HyperedgeIndex
from hyperbench.utils import Stage
from hyperbench.nn import HyperedgeAggregator

from hyperbench.hlp.hlp import HlpModule


class Node2VecEncoderConfig(TypedDict):
    """
    Configuration for the Node2Vec encoder in ``Node2VecHlpModule``.

    Args:
        mode: Whether to use precomputed node embeddings from ``x`` or train a Node2Vec encoder jointly inside the module.
        num_features: Dimension of the node embeddings consumed by the decoder.
        walk_length: Length of each random walk.
        context_size: Skip-gram context size for Node2Vec.
            For example, if ``context_size=2`` and ``walk_length=5``, then for a random walk ``[v0, v1, v2, v3, v4]``,
            the context for ``v2`` would be ``[v0, v1, v3, v4]`` as we take neighbors within distance 2 in the walk.
            The pairs generated by skip-gram would be ``[(v2, v0), (v2, v1), (v2, v3), (v2, v4)]``.
            Rule of thumb: Graphs with strong local structure (5-10), Graphs with communities/long-range patterns (10-20).
            Defaults to ``10``.
        num_walks_per_node: Number of walks sampled per node.
        p: Node2Vec return parameter. Controls the probability of stepping back to the node visited
            in the previous step. Lower values of ``p`` make immediate backtracking more likely,
            while higher values discourage returning to the previous node.
        q: Node2Vec in-out parameter. Controls whether walks stay near the source node or explore
            further outward. Lower values of ``q`` bias the walk toward DFS-like exploration and
            structural similarity, while higher values bias it toward BFS-like exploration and
            local community structure and homophily.
        num_negative_samples: Number of negative samples per positive walk context.
            If set to ``X``, then for each positive pair ``(u, v)`` generated from the random walks,
            ``X`` negative pairs ``(u, v_neg)`` will be generated,
            where ``v_neg`` is a node sampled uniformly at random from all nodes in the graph.
            Defaults to ``1``, meaning one negative sample per positive pair.
        num_nodes: Number of nodes in the stable node space. Defaults to the number of nodes in the ``hyperedge_index`` if not provided.
        train_hyperedge_index: Training hypereddge index used to build the Node2Vec walk graph. Required in ``joint`` mode.
        graph_reduction_strategy: Strategy for reducing the hyperedge graph. Defaults to ``clique_expansion``.
        random_walk_batch_size: Batch size used by the walk sampler in joint mode.
        node2vec_loss_weight: Weight applied to the Node2Vec walk loss in joint mode.
            This is to decide how much the loss of Node2Vec contributes to the overall loss in joint training, relative to the HLP loss.
             Defaults to ``1.0`` (equal weighting). Set to a higher value to prioritize learning good node embeddings,
             or a lower value to prioritize the HLP loss. Ignored in precomputed mode.
    """

    mode: NotRequired[Literal["precomputed", "joint"]]
    num_features: int
    context_size: NotRequired[int]
    walk_length: NotRequired[int]
    num_walks_per_node: NotRequired[int]
    p: NotRequired[float]
    q: NotRequired[float]
    num_negative_samples: NotRequired[int]
    num_nodes: NotRequired[int]
    train_hyperedge_index: NotRequired[Tensor]
    graph_reduction_strategy: NotRequired[Literal["clique_expansion"]]
    random_walk_batch_size: NotRequired[int]
    node2vec_loss_weight: NotRequired[float]


class Node2VecSLPHlpModule(HlpModule):
    """
    A LightningModule for Node2Vec-based Hyperedge Link Prediction.

    Supports two modes:
    - ``precomputed``: use node embeddings already stored in ``batch.x``.
    - ``joint``: train a Node2Vec encoder jointly with the hyperedge decoder.

    Args:
        encoder_config: Configuration for the Node2Vec encoder.
        aggregation: Method to aggregate node embeddings per hyperedge.
        loss_fn: Loss function. Defaults to ``BCEWithLogitsLoss``.
        lr: Learning rate for the optimizer. Defaults to ``0.001``.
        weight_decay: Weight decay (L2 regularization) for the optimizer. Defaults to ``0.0`` (no weight decay).
        metrics: Optional dictionary of metric functions.
    """

    JOINT_MODE = "joint"
    PRECOMPUTED_MODE = "precomputed"

    def __init__(
        self,
        encoder_config: Node2VecEncoderConfig,
        aggregation: Literal["mean", "max", "min", "sum"] = "mean",
        loss_fn: Optional[nn.Module] = None,
        lr: float = 0.001,
        weight_decay: float = 0.0,
        metrics: Optional[MetricCollection] = None,
    ):
        self.mode = encoder_config.get("mode", self.JOINT_MODE)
        self.embedding_dim = encoder_config["num_features"]
        self.num_nodes = encoder_config.get("num_nodes")

        if self.mode == self.JOINT_MODE:
            if "train_hyperedge_index" not in encoder_config:
                raise ValueError(f"Node2Vec in mode {self.mode} requires train_hyperedge_index.")

            walk_length = encoder_config.get("walk_length", 20)
            context_size = encoder_config.get("context_size", 10)
            if walk_length < context_size:
                raise ValueError(
                    f"Expected walk_length >= context_size, got "
                    f"walk_length={walk_length}, context_size={context_size}."
                )

            reduced_edge_index = HyperedgeIndex(encoder_config["train_hyperedge_index"]).reduce(
                encoder_config.get("graph_reduction_strategy", "clique_expansion")
            )
            edge_index_wrapper = EdgeIndex(reduced_edge_index).remove_selfloops()

            encoder = Node2Vec(
                edge_index=edge_index_wrapper.item,
                embedding_dim=self.embedding_dim,
                walk_length=walk_length,
                context_size=context_size,
                num_walks_per_node=encoder_config.get("num_walks_per_node", 10),
                p=encoder_config.get("p", 1.0),
                q=encoder_config.get("q", 1.0),
                num_negative_samples=encoder_config.get("num_negative_samples", 1),
                num_nodes=self.num_nodes
                if self.num_nodes is not None
                else edge_index_wrapper.num_nodes,
                sparse=False,
            )
        else:
            # We don't need an encoder in precomputed mode
            # since node features are used as node embeddings
            encoder = None

        decoder = SLP(in_channels=self.embedding_dim, out_channels=1)

        super().__init__(
            encoder=encoder,
            decoder=decoder,
            loss_fn=loss_fn if loss_fn is not None else nn.BCEWithLogitsLoss(),
            metrics=metrics,
        )

        self.aggregation = aggregation
        self.lr = lr
        self.weight_decay = weight_decay
        self.random_walk_batch_size = encoder_config.get("random_walk_batch_size", 128)
        self.node2vec_loss_weight = encoder_config.get("node2vec_loss_weight", 1.0)

        self.__walk_loader: Optional[DataLoader] = None
        self.__cached_walk_loader_iterator: Optional[Iterator] = None

    def forward(
        self,
        x: Tensor,
        hyperedge_index: Tensor,
        global_node_ids: Optional[Tensor] = None,
    ) -> Tensor:
        # Encode: get node embeddings from precomputation or joint encoder
        if self.mode == self.JOINT_MODE:
            encoder = self.__node2vec_encoder()
            self.__validate_global_node_ids(encoder.num_embeddings, global_node_ids)
            node_embeddings = encoder(batch=global_node_ids)
        else:
            if x.size(1) != self.embedding_dim:
                raise ValueError(
                    f"Expected precomputed node embeddings with dimension "
                    f"{self.embedding_dim}, got {x.size(1)}."
                )
            node_embeddings = x

        # Aggregate: pool node embeddings per hyperedge
        # shape: (num_hyperedges, embedding_dim)
        hyperedge_embeddings = HyperedgeAggregator(hyperedge_index, node_embeddings).pool(
            self.aggregation
        )

        # Decode: linear projection to scalar score per hyperedge
        # shape: (num_hyperedges, 1) -> squeeze -> (num_hyperedges,)
        scores: Tensor = self.decoder(hyperedge_embeddings).squeeze(-1)
        return scores

    def training_step(self, batch: HData, batch_idx: int) -> Tensor:
        scores = self.forward(batch.x, batch.hyperedge_index, batch.global_node_ids)
        labels = batch.y
        batch_size = batch.num_hyperedges

        if self.mode == self.JOINT_MODE:
            # Node2Vec.loss() is already a stochastic objective over sampled walks,
            # so one walk batch is a standard SGD estimate, not a logically different loss,
            # meaning we can optimize training by using a single walk batch per training step,
            # instead of averaging over multiple walk batches.
            positive_random_walk, negative_random_walk = self.__next_walk_batch()
            positive_random_walk = positive_random_walk.to(self.device)
            negative_random_walk = negative_random_walk.to(self.device)

            hlp_loss = self.loss_fn(scores, labels)
            node2vec_loss = self.__node2vec_encoder().loss(
                positive_random_walk,
                negative_random_walk,
            )
            loss = hlp_loss + (self.node2vec_loss_weight * node2vec_loss)

            loss_prefix = Stage.TRAIN.value
            self.log(f"{loss_prefix}_hlp_loss", hlp_loss, prog_bar=True, batch_size=batch_size)
            self.log(
                f"{loss_prefix}_node2vec_loss", node2vec_loss, prog_bar=True, batch_size=batch_size
            )
            self.log(f"{loss_prefix}_loss", loss, prog_bar=True, batch_size=batch_size)
        else:
            loss = self._compute_loss(scores, labels, batch_size, Stage.TRAIN)

        self._compute_metrics(scores, labels, batch_size, Stage.TRAIN)
        return loss

    def validation_step(self, batch: HData, batch_idx: int) -> Tensor:
        return self.__eval_step(batch, Stage.VAL)

    def test_step(self, batch: HData, batch_idx: int) -> Tensor:
        return self.__eval_step(batch, Stage.TEST)

    def predict_step(self, batch: HData, batch_idx: int) -> Tensor:
        return self.forward(batch.x, batch.hyperedge_index, batch.global_node_ids)

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=self.lr, weight_decay=self.weight_decay)

    def __eval_step(self, batch: HData, stage: Stage) -> Tensor:
        scores = self.forward(batch.x, batch.hyperedge_index, batch.global_node_ids)
        labels = batch.y
        batch_size = batch.num_hyperedges

        loss = self._compute_loss(scores, labels, batch_size, stage)
        self._compute_metrics(scores, labels, batch_size, stage)
        return loss

    def __get_walk_loader(self) -> Optional[DataLoader]:
        if self.mode != "joint":  # Walk loader is only needed in joint mode
            return None

        if self.__walk_loader is None:
            self.__walk_loader = self.__node2vec_encoder().loader(
                batch_size=self.random_walk_batch_size,
                shuffle=True,
            )
            self.__cached_walk_loader_iterator = iter(self.__walk_loader)

        return self.__walk_loader

    def __next_walk_batch(self):
        self.__get_walk_loader()
        if self.__walk_loader is None or self.__cached_walk_loader_iterator is None:
            raise ValueError("Joint Node2Vec mode could not initialize the walk loader.")

        try:
            return next(self.__cached_walk_loader_iterator)
        except StopIteration:
            # Create a new iterator as we exhausted the existing one
            self.__cached_walk_loader_iterator = iter(self.__walk_loader)
            return next(self.__cached_walk_loader_iterator)

    def __node2vec_encoder(self) -> Node2Vec:
        if self.encoder is None or not isinstance(self.encoder, Node2Vec):
            raise ValueError(
                f"Node2Vec in mode {self.mode} requires an encoder, but none was provided."
            )
        return self.encoder

    def __validate_global_node_ids(self, num_embeddings: int, global_node_ids: Optional[Tensor]):
        if global_node_ids is None or len(global_node_ids) < 1:
            raise ValueError(f"Node2Vec in mode {self.mode} requires batch.global_node_ids.")

        min_global_node_id = int(global_node_ids.min().item())
        max_global_node_id = int(global_node_ids.max().item())

        max_acceptable_node_id = num_embeddings - 1
        if min_global_node_id < 0 or max_global_node_id > max_acceptable_node_id:
            raise ValueError(
                f"Node2Vec in mode {self.mode} cannot index the provided batch.global_node_ids. "
                f"Expected IDs in [0, {max_acceptable_node_id}], got "
                f"[{min_global_node_id}, {max_global_node_id}]. "
                "Set encoder_config['num_nodes'] for the full stable node space."
            )
