# https://stackoverflow.com/questions/79382491/how-to-proactively-enforce-branch-naming-convention-in-github
name: Branch Naming Convention Check
on:
  create:
    branches:
    - '**'

permissions:
  contents: read

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch name
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}

        VALID_PATTERNS="^(feat|fix|chore|refactor|docs)\/[a-z0-9]+(-[a-z0-9]+)*$|^v*$"

        if ! [[ $BRANCH_NAME =~ $VALID_PATTERNS ]]; then
          echo "Branch name (${BRANCH_NAME}) is invalid."
          echo "It must follow the naming convention: 'feat|fix|chore|refactor|docs/<name>' for branches or 'v*' for tags."
          exit 1
        fi
