name: Documentation

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      with:
        persist-credentials: false

    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e .
        uv pip install zensical mkdocstrings[python]
        uv run zensical build --clean

    - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
      with:
        path: docs/site

    - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
      id: deployment
